export const ADD_FAV = 'ADD_FAV';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CATEGORIES_FAIL = 'CATEGORIES_FAIL';
export const SELECTED_CATEGORY ='SELECTED_CATEGORY'
export const SELECTED_CATEGORIES ='SELECTED_CATEGORIES'
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORY_DETAIL = 'CATEGORY_DETAIL'